# Generated by Django 4.2.6 on 2024-11-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(
                        db_column="User_ID",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ユーザID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="Name", max_length=30, verbose_name="ユーザ名"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        db_column="Password", max_length=512, verbose_name="パスワード"
                    ),
                ),
                (
                    "mailaddress",
                    models.CharField(
                        db_column="MailAddress",
                        max_length=128,
                        unique=True,
                        verbose_name="メールアドレス",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        db_column="Gender", max_length=1, verbose_name="性別"
                    ),
                ),
                (
                    "age",
                    models.CharField(
                        db_column="Age", max_length=10, verbose_name="生年月日"
                    ),
                ),
                ("height", models.FloatField(db_column="Height", verbose_name="身長")),
                ("weight", models.FloatField(db_column="Weight", verbose_name="体重")),
                (
                    "admin",
                    models.BooleanField(db_column="Admin", verbose_name="管理者フラグ"),
                ),
                (
                    "family",
                    models.BooleanField(db_column="Family", verbose_name="家族フラグ"),
                ),
                (
                    "logindate",
                    models.CharField(
                        db_column="LoginDate", max_length=10, verbose_name="ログイン日時"
                    ),
                ),
                (
                    "deleteflag",
                    models.BooleanField(db_column="DeleteFlag", verbose_name="削除フラグ"),
                ),
                (
                    "subscribeflag",
                    models.BooleanField(
                        db_column="SubscribeFlag", verbose_name="サブスクフラグ"
                    ),
                ),
                (
                    "subjoin",
                    models.CharField(
                        blank=True,
                        db_column="SubJoin",
                        max_length=20,
                        null=True,
                        verbose_name="サブスク入会日付",
                    ),
                ),
                (
                    "unsub",
                    models.CharField(
                        blank=True,
                        db_column="UnSub",
                        max_length=20,
                        null=True,
                        verbose_name="サブスク退会日付",
                    ),
                ),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
    ]
