# Generated by Django 4.2.6 on 2025-01-31 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Allergy",
            fields=[
                (
                    "allergy_id",
                    models.AutoField(
                        db_column="ALLERGY_ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="アレルギーID",
                    ),
                ),
                (
                    "material_id",
                    models.IntegerField(db_column="MATERIAL_ID", verbose_name="材料ID"),
                ),
                (
                    "allergy_category",
                    models.CharField(
                        db_column="ALLERGY_CATEGORY",
                        max_length=30,
                        verbose_name="アレルギーカテゴリー",
                    ),
                ),
                (
                    "allergy_name",
                    models.CharField(
                        db_column="ALLERGY_NAME", max_length=30, verbose_name="アレルギー名"
                    ),
                ),
            ],
            options={
                "db_table": "allergy",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Familyallergy",
            fields=[
                (
                    "family_allergy_id",
                    models.AutoField(
                        db_column="FamilyAllergyID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="家族アレルギーID",
                    ),
                ),
            ],
            options={
                "db_table": "familyallergy",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Familymember",
            fields=[
                (
                    "family_id",
                    models.AutoField(
                        db_column="Family_ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "family_name",
                    models.CharField(db_column="Family_Name", max_length=30),
                ),
                (
                    "family_gender",
                    models.CharField(db_column="Family_Gender", max_length=1),
                ),
                ("family_age", models.CharField(db_column="Family_Age", max_length=10)),
                ("family_height", models.FloatField(db_column="Family_Height")),
                ("family_weight", models.FloatField(db_column="Family_Weight")),
            ],
            options={
                "db_table": "familymember",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "news_id",
                    models.AutoField(
                        db_column="NEWS_ID", primary_key=True, serialize=False
                    ),
                ),
                ("content", models.TextField(db_column="Content")),
                (
                    "upload_time",
                    models.CharField(db_column="UploadTime", max_length=20),
                ),
                (
                    "update_time",
                    models.CharField(
                        blank=True, db_column="UpdateTime", max_length=20, null=True
                    ),
                ),
                ("title", models.CharField(db_column="title", max_length=100)),
            ],
            options={
                "db_table": "News",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Newsimage",
            fields=[
                (
                    "newsimage_id",
                    models.AutoField(
                        db_column="NEWSIMAGE_ID", primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "db_table": "NewsImage",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "qustion_id",
                    models.IntegerField(
                        db_column="Qustion_ID", primary_key=True, serialize=False
                    ),
                ),
                ("qustion", models.TextField(db_column="Qustion")),
                ("answer", models.TextField(db_column="Answer")),
            ],
            options={
                "db_table": "Question",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Weight",
            fields=[
                (
                    "weight_id",
                    models.AutoField(
                        db_column="Weight_ID", primary_key=True, serialize=False
                    ),
                ),
                ("weight", models.FloatField(db_column="Weight")),
                (
                    "registertime",
                    models.CharField(db_column="RegisterTime", max_length=50),
                ),
            ],
            options={
                "db_table": "weight",
                "managed": False,
            },
        ),
    ]
