# Generated by Django 4.2.6 on 2024-11-25 00:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cookapp", "0003_allergy_weight"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
        migrations.DeleteModel(
            name="Userallergy",
        ),
    ]
