# Generated by Django 4.2.5 on 2024-11-28 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0004_delete_user_delete_userallergy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymember',
            options={},
        ),
        migrations.AlterModelOptions(
            name='weight',
            options={},
        ),
    ]
