# Generated by Django 4.2.5 on 2025-01-15 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookapp', '0005_alter_familymember_options_alter_weight_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='family_id',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='user_id',
        ),
        migrations.AddField(
            model_name='familymember',
            name='user',
            field=models.ForeignKey(db_column='User_ID', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weight',
            name='family',
            field=models.ForeignKey(db_column='Family_ID', default=1, on_delete=django.db.models.deletion.CASCADE, to='cookapp.familymember'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weight',
            name='user',
            field=models.ForeignKey(db_column='User_ID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_weights', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='familymember',
            name='family_age',
            field=models.CharField(db_column='Family_Age', max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='family_gender',
            field=models.CharField(db_column='Family_Gender', max_length=1),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='family_height',
            field=models.FloatField(db_column='Family_Height'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='family_id',
            field=models.AutoField(db_column='Family_ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='family_name',
            field=models.CharField(db_column='Family_Name', max_length=30),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='family_weight',
            field=models.FloatField(db_column='Family_Weight'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='register_time',
            field=models.CharField(db_column='RegisterTime', max_length=50),
        ),
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.FloatField(db_column='Weight'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='weight_id',
            field=models.AutoField(db_column='Weight_ID', primary_key=True, serialize=False),
        ),
    ]
