# Generated by Django 4.2.5 on 2025-01-24 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0006_remove_weight_family_id_remove_weight_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='family',
            field=models.ForeignKey(db_column='Family_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='cookapp.familymember'),
        ),
    ]
