# Generated by Django 4.2.5 on 2024-11-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bbs',
            fields=[
                ('post_id', models.AutoField(db_column='POST_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=60)),
                ('recipe_text', models.TextField(db_column='RECIPE_TEXT')),
                ('post_time', models.DateTimeField(auto_now_add=True, db_column='POST_TIME')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='UPDATE_TIME', null=True)),
                ('calorie', models.FloatField(db_column='calorie')),
                ('protein', models.FloatField(db_column='protein')),
                ('lipids', models.FloatField(db_column='lipids')),
                ('fiber', models.FloatField(db_column='fiber')),
                ('carbohydrates', models.FloatField(db_column='carbohydrates')),
                ('saltcontent', models.FloatField(db_column='saltcontent')),
            ],
            options={
                'db_table': 'bbs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Postimage',
            fields=[
                ('postimage_id', models.AutoField(db_column='POSTIMAGE_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'postimage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userrecipe',
            fields=[
                ('userrecipe_id', models.AutoField(db_column='USERRECIPE_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'userrecipe',
                'managed': False,
            },
        ),
    ]
