# Generated by Django 4.2.6 on 2025-02-05 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("administrator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bbs",
            fields=[
                (
                    "post_id",
                    models.AutoField(
                        db_column="POST_ID", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="name", max_length=60)),
                ("recipe_text", models.TextField(db_column="RECIPE_TEXT")),
                (
                    "post_time",
                    models.DateTimeField(auto_now_add=True, db_column="POST_TIME"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, db_column="UPDATE_TIME", null=True
                    ),
                ),
                ("calorie", models.FloatField(db_column="calorie")),
                ("protein", models.FloatField(db_column="protein")),
                ("lipids", models.FloatField(db_column="lipids")),
                ("fiber", models.FloatField(db_column="fiber")),
                ("carbohydrates", models.FloatField(db_column="carbohydrates")),
                ("saltcontent", models.FloatField(db_column="saltcontent")),
                (
                    "user",
                    models.ForeignKey(
                        db_column="USER_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bbs",
            },
        ),
        migrations.CreateModel(
            name="Userrecipe",
            fields=[
                (
                    "userrecipe_id",
                    models.AutoField(
                        db_column="USERRECIPE_ID", primary_key=True, serialize=False
                    ),
                ),
                ("quantity", models.IntegerField(db_column="material_quantity")),
                (
                    "material",
                    models.ForeignKey(
                        db_column="MATERIAL_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrator.material",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        db_column="POST_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bbs.bbs",
                    ),
                ),
            ],
            options={
                "db_table": "userrecipe",
            },
        ),
        migrations.CreateModel(
            name="Postimage",
            fields=[
                (
                    "postimage_id",
                    models.AutoField(
                        db_column="POSTIMAGE_ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        db_column="IMAGE_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrator.image",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        db_column="POST_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bbs.bbs",
                    ),
                ),
            ],
            options={
                "db_table": "postimage",
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "favorite_id",
                    models.AutoField(
                        db_column="FAVORITE_ID", primary_key=True, serialize=False
                    ),
                ),
                ("favorite_flag", models.BooleanField(db_column="FAVORITE_FLAG")),
                (
                    "post",
                    models.ForeignKey(
                        db_column="POST_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bbs.bbs",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="USER_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "favorite",
            },
        ),
    ]
