# Generated by Django 4.2.5 on 2024-11-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bbs',
            fields=[
                ('post_id', models.AutoField(db_column='POST_ID', primary_key=True, serialize=False)),
                ('recipe_text', models.TextField(db_column='RECIPE_TEXT')),
                ('post_time', models.CharField(db_column='POST_TIME', max_length=20)),
                ('update_time', models.CharField(blank=True, db_column='UPDATE_TIME', max_length=20, null=True)),
            ],
            options={
                'db_table': 'bbs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Postimage',
            fields=[
                ('postimage_id', models.AutoField(db_column='POSTIMAGE_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'postimage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userrecipe',
            fields=[
                ('userrecipe_id', models.AutoField(db_column='USERRECIPE_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'userrecipe',
                'managed': False,
            },
        ),
    ]
