# Generated by Django 4.2.5 on 2025-01-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('favorite_id', models.AutoField(db_column='FAVORITE_ID', primary_key=True, serialize=False)),
                ('favorite_flag', models.BooleanField(db_column='FAVORITE_FLAG')),
            ],
            options={
                'db_table': 'favorite',
                'managed': False,
            },
        ),
    ]
