# Generated by Django 4.2.6 on 2025-02-04 03:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("administrator", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AdministratorCookimagesave",
            new_name="Cookimagesave",
        ),
    ]
